version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/static:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
